openapi: 3.0.1
info:
  title: Banco XYZ API
  description: API para gestionar usuarios y cuentas de banco XYZ.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /clientes:
    get:
      summary: Listar todos los clientes
      operationId: listCustomers
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        'default':
          description: Error en la obtención de clientes
    post:
      summary: Crear nuevo cliente
      operationId: createCustomer
      requestBody:
        description: Objeto cliente que necesita ser creado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Cliente creado
        'default':
          description: Error en la creación del cliente

  /clientes/{id}:
    get:
      summary: Obtener cliente por su ID
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalles de cliente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        'default':
          description: Error en la obtención del cliente
    put:
      summary: Actualizar cliente por su ID
      operationId: updateCustomerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Objeto cliente actualizado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Cliente actualizado
        'default':
          description: Error en la actualización del cliente
    delete:
      summary: Eliminar cliente por su ID
      operationId: deleteCustomerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Cliente eliminado
        'default':
          description: Error al eliminar el cliente

  /cuentas:
    get:
      summary: Listar todas las cuentas
      operationId: listAccounts
      responses:
        '200':
          description: Lista de cuentas bancarias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        'default':
          description: Error en la obtención de cuentas
    post:
      summary: Crear una nueva cuenta
      operationId: createAccount
      requestBody:
        description: Objeto cuenta que necesita ser creado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: Cuenta creada
        'default':
          description: Error en la creación de la cuenta

  /cuentas/{id}:
    get:
      summary: Obtener cuenta por su ID
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalles de cuenta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        'default':
          description: Error en la obtención de la cuenta
    delete:
      summary: Eliminar cuenta por su ID
      operationId: deleteAccountById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Cuenta eliminada
        'default':
          description: Error al eliminar la cuenta

  /cuentas/{id}/depositar:
    put:
      summary: Depositar dinero en una cuenta
      operationId: depositIntoAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Monto a depositar
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: double
      responses:
        '200':
          description: Depósito exitoso
        'default':
          description: Error en el depósito

  /cuentas/{id}/retirar:
    put:
      summary: Retirar dinero de una cuenta
      operationId: withdrawFromAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Monto a retirar
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: double
      responses:
        '200':
          description: Retiro exitoso
        'default':
          description: Error en el retiro

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        apellido:
          type: string
        dni:
          type: string
        email:
          type: string
      required:
        - nombre
        - apellido
        - dni
        - email

    Account:
      type: object
      properties:
        id:
          type: integer
        numeroCuenta:
          type: string
        saldo:
          type: number
          format: double
        tipoCuenta:
          type: string
          enum:
            - AHORROS
            - CORRIENTE
        clienteId:
          type: integer
      required:
        - numeroCuenta
        - saldo
        - tipoCuenta
        - clienteId
